<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>RF4AssistantPro</RootNamespace>
    <AssemblyName>RF4Assistant.Core</AssemblyName>
  </PropertyGroup>
</Project>
